# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Customer.create(firstname:"Jason", lastname:"Alexander", email:"seinfeldfunnyguy@gmail.com", phone:"7908781234", address1:"1234 Goofball St.", city:"New York", state:"NY", zip:"11365")
# Customer.create(firstname:"Tony", lastname:"Turnip", email:"Morrowindman@gmail.com", phone:"3789765542", address1:"7777 Busy Blvd.", city:"Detroit", state:"MI", zip:"48009")
# Customer.create(firstname:"Mary", lastname:"Shelley", email:"Frankensteingirl666@gmail.com", phone:"1235558787", address1:"7171 Paradise St.", city:"New York", state:"NY", zip:"11365")
# Customer.create(firstname:"Herman", lastname:"Melville", email:"whitewhale@yahoo.com", phone:"8881231234", address1:"8080 Starbuck Ln.", city:"Nantucket", state:"MA", zip:"02554")
# Customer.create(firstname:"John", lastname:"Egbert", email:"ectobiologist@pesterchum.net", phone:"4136128888", address1:"3232 Crocker St.", city:"Sburbia", state:"NJ", zip:"12345")
# Customer.create(firstname:"Tony", lastname:"Tiger", email:"cerealdaddy@gmail.com", phone:"2758134565", address1:"3454 Bara Blvd.", city:"Battle Creek", state:"MI", zip:"48124")
# Customer.create(firstname:"Stanley", lastname:"Kowalski", email:"Stellaaaaa@gmail.com", phone:"8761234565", address1:"555 Elysian Fields", city:"New Orleans", state:"LA", zip:"12345")
# Customer.create(firstname:"Dante", lastname:"Alighieri", email:"NoticeMeBeatrice@gmail.com", phone:"6667778888", address1:"9 Circle St.", city:"Hell", state:"MI", zip:"48169")
# Customer.create(firstname:"Zach", lastname:"Hill", email:"gottagoogle@gmail.com", phone:"23212345656", address1:"777 Chateau Rd.", city:"Sacramento", state:"CA", zip:"77889")
# Customer.create(firstname:"Johnny", lastname:"Law", email:"iamacop@aol.com", phone:"2487871234", address1:"5676 Law Ln.", city:"Chicago", state:"IL", zip:"60614")


# Transaction.create(customer_id:"1", saledate:"1/1/2019", salesnotes:"First Sale!")
# Transaction.create(customer_id:"2", saledate:"1/3/2019", salesnotes:"")
# Transaction.create(customer_id:"3", saledate:"1/4/2019", salesnotes:"")
# Transaction.create(customer_id:"4", saledate:"1/14/2019", salesnotes:"")
# Transaction.create(customer_id:"5", saledate:"1/21/2019", salesnotes:"")
# Transaction.create(customer_id:"6", saledate:"2/5/2019", salesnotes:"")
# Transaction.create(customer_id:"7", saledate:"2/8/2019", salesnotes:"")
# Transaction.create(customer_id:"8", saledate:"2/12/2019", salesnotes:"")
# Transaction.create(customer_id:"9", saledate:"2/15/2019", salesnotes:"")
# Transaction.create(customer_id:"10", saledate:"2/18/2019", salesnotes:"")

# Trandetail.create(transaction_id:"1", product_id:"1", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"2", product_id:"2", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"3", product_id:"4", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"4", product_id:"6", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"5", product_id:"1", saleprice:"20", prodqty:"99")
# Trandetail.create(transaction_id:"6", product_id:"3", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"7", product_id:"2", saleprice:"20", prodqty:"99")
# Trandetail.create(transaction_id:"8", product_id:"5", saleprice:"20", prodqty:"100")
# Trandetail.create(transaction_id:"9", product_id:"5", saleprice:"20", prodqty:"99")
# Trandetail.create(transaction_id:"10", product_id:"6", saleprice:"20", prodqty:"99")

# Category.create(categoryname:"hats", description:"Baseball caps, beanies etc.")
# Category.create(categoryname:"tshirt", description:"short sleeves")
# Category.create(categoryname:"shirt", description:"long sleeves")
# Category.create(categoryname:"hoodie", description:"hoodies")
# Category.create(categoryname:"sleeveless", description:"no sleeves")
# Category.create(categoryname:"zip", description:"zipper hoodie")
# Category.create(categoryname:"athfit", description:"athletic fit")
# Category.create(categoryname:"ladies", description:"clothes for the girls")
# Category.create(categoryname:"gents", description:"clothes for the boys")
# Category.create(categoryname:"cozy", description:"warm clothes")

# Product.create(productname:"small white shirt design 1", productimage:"1", description:"shirt design 1 in white S", color:"white", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"medium white shirt design 1", productimage:"1", description:"shirt design 1 in white M", color:"white", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"large white shirt design 1", productimage:"1", description:"shirt design 1 in white L", color:"white", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"small black shirt design 1", productimage:"2", description:"shirt design 1 in black S", color:"black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"medium black shirt design 1", productimage:"2", description:"shirt design 1 in black M", color:"black", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"large black shirt design 1", productimage:"2", description:"shirt design 1 in black L", color:"black", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"small white shirt design 2", productimage:"3", description:"shirt design 2 in white S", color:"white", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"medium white shirt design 2", productimage:"3", description:"shirt design 2 in white M", color:"white", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"large white shirt design 2", productimage:"3", description:"shirt design 2 in white L", color:"white", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")
# Product.create(productname:"small black shirt design 2", productimage:"4", description:"shirt design 2 in black S", color:"black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"25", qtyonhand:"", reorderpoint:"", reorderqty:"")

# Supplier.create(companyname:"Red Bubble", pointofcontact:"redbubblesupport@redbubble.com", website:"redbubble.com", phone:"8887651234")
# Supplier.create(companyname:"Custom Ink", pointofcontact:"custominksupport@customink.com", website:"customink.com", phone:"8885654343")
# Supplier.create(companyname:"Rush Order Tees", pointofcontact:"rushordersupport@rushorder.com", website:"rushordertees.com", phone:"8882675337")
# Supplier.create(companyname:"Underground Shirts", pointofcontact:"undergroundshirtssupport@undergroundshirts.com", website:"undergroundshirts.com", phone:"8006563123")
# Supplier.create(companyname:"Vista Print", pointofcontact:"vistaprintcontact@gmail.com", website:"vistaprintcontact@vistaprint.com", phone:"8006754321")
# Supplier.create(companyname:"Broken Arrow", pointofcontact:"brokenarrowsupport@brokenarrow.com", website:"brokenarrowwear.com", phone:"88812346543")
# Supplier.create(companyname:"Zazzle", pointofcontact:"zazzlesupport@zazzle.com", website:"zazzle.com", phone:"8009876543")
# Supplier.create(companyname:"Lucky Prints", pointofcontact:"contactluckyprints@luckyprints.com", website:"luckyprints.com", phone:"8009998765")
# Supplier.create(companyname:"Printful", pointofcontact:"printfulhelpme@printful.com", website:"printful.com", phone:"8001234543")
# Supplier.create(companyname:"Uber Prints", pointofcontact:"uberprintssupport@uberprints.com", website:"uberprints.com", phone:"8009875832")

# Advertisement.create(title: "Advertisement 1", description: "Advertisement 1 Desc", imagepath: "samsung.png", startdate: "2019-01-01", enddate: "2019-01-31")
# Advertisement.create(title: "Advertisement 2", description: "Advertisement 2 Desc", imagepath: "apple.png", startdate: "2019-02-01", enddate: "2019-02-28")
# Advertisement.create(title: "Advertisement 3", description: "Advertisement 3 Desc", imagepath: "motorola.png", startdate: "2019-02-01", enddate: "2019-03-31")
# Advertisement.create(title: "Advertisement 4", description: "Advertisement 4 Desc", imagepath: "acer.png", startdate: "2019-04-01", enddate: "2019-05-31")
# Advertisement.create(title: "Advertisement 5", description: "Advertisement 5 Desc", imagepath: "dell.png", startdate: "2019-06-01", enddate: "2019-06-30")

# Promotion.create(title: "Advertisement 1", description: "Advertisement 1 Desc", imagepath: "whiteshirtad.png", startdate: "2019-01-01", enddate: "2019-01-31")
# Promotion.create(title: "Advertisement 2", description: "Advertisement 2 Desc", imagepath: "blackshirtad.png", startdate: "2019-02-01", enddate: "2019-02-28")
# Promotion.create(title: "Advertisement 3", description: "Advertisement 3 Desc", imagepath: "whiteshirtad2.png", startdate: "2019-02-01", enddate: "2019-03-31")
# Promotion.create(title: "Advertisement 4", description: "Advertisement 4 Desc", imagepath: "blackshirtad2.png", startdate: "2019-04-01", enddate: "2019-05-31")
# Promotion.create(title: "Advertisement 5", description: "Advertisement 5 Desc", imagepath: "whiteshirtad3.png", startdate: "2019-06-01", enddate: "2019-06-30")

Product.create(productname:"Small Twin Peaks White", productimage:"2", description:"Small White Twin Peaks Shirt", color:"White", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Twin Peaks White", productimage:"2", description:"Medium White Twin Peaks Shirt", color:"White", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Twin Peaks White", productimage:"2", description:"Large White Twin Peaks Shirt", color:"White", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Magician Black", productimage:"3", description:"Small Black Magician Shirt", color:"Black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Magician Black", productimage:"3", description:"Medium Black Magician Shirt", color:"Black", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Magician Black", productimage:"3", description:"Large Black Magician Shirt", color:"Black", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Magician White", productimage:"4", description:"Small White Magician Shirt", color:"White", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Magician White", productimage:"4", description:"Medium White Magician Shirt", color:"White", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Magician White", productimage:"4", description:"Large White Magician Shirt", color:"White", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Smoke Black", productimage:"5", description:"Small Black Smoke Shirt", color:"Black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Smoke Black", productimage:"5", description:"Medium Black Smoke Shirt", color:"Black", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Smoke Black", productimage:"5", description:"Large Black Shirt", color:"Black", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Smoke White", productimage:"6", description:"Small White Smoke Shirt", color:"White", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Smoke White", productimage:"6", description:"Medium White Smoke Shirt", color:"White", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Smoke White", productimage:"6", description:"Large White Shirt", color:"White", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Streaky Black", productimage:"7", description:"Small Black Streaky Shirt", color:"Black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Streaky Black", productimage:"7", description:"Medium Black Streaky Shirt", color:"Black", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Streaky Black", productimage:"7", description:"Large Streaky Shirt", color:"Black", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Streaky White", productimage:"8", description:"Small White Streaky Shirt", color:"White", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Streaky White", productimage:"8", description:"Medium White Streaky Shirt", color:"White", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Streaky White", productimage:"8", description:"Large White Streaky Shirt", color:"White", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Demon Goggles Black", productimage:"9", description:"Small Black Demon Goggles Shirt", color:"Black", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Demon Goggles Black", productimage:"9", description:"Medium Black Demon Goggles Shirt", color:"Black", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Demon Goggles Black", productimage:"9", description:"Large Black Demon Goggles Shirt", color:"Black", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")

Product.create(productname:"Small Demon Goggles White", productimage:"10", description:"Small White Demon Goggles Shirt", color:"White", size:"S", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Medium Demon Goggles White", productimage:"10", description:"Medium White Demon Goggles Shirt", color:"White", size:"M", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")
Product.create(productname:"Large Demon Goggles White", productimage:"10", description:"Large White Demon Goggles Shirt", color:"White", size:"L", subcategory1:"", saleprice:"20", status:"", purchaseprice:"20", qtyonhand:"", reorderpoint:"", reorderqty:"")